root = '/Users/marcWong/Dataset/ningbo3539_edge_aug/test/';

%fid = fopen('/Users/marcWong/Desktop/lab/ningbo3539_edge_gt/test.lst','w');
fid = fopen('/Users/marcWong/Dataset/ningbo3539_edge_aug/train_pair.lst','w');

listing = dir([root '*.jpg']);
fileSum = length(listing);

for imgNum=1:fileSum
    %tx1 = ['test/' listing(imgNum).name];
    %fprintf(fid,'%s\n',tx1);
    
    tx1 = ['train/aug_data/0.0_1_0/' listing(imgNum).name];
    tx2 = ['train/aug_gt/0.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
    fprintf(fid,'%s %s\n',tx1,tx2);
    tx1 = ['train/aug_data/0.0_1_1/' listing(imgNum).name];
    tx2 = ['train/aug_gt/0.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
    fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/0.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/0.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/0.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/0.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/0.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/0.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/0.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/0.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     
%     tx1 = ['train/aug_data/22.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/22.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data/22.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/22.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/22.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/22.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/22.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/22.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/22.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/22.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/22.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/22.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
%     tx1 = ['train/aug_data/45.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/45.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data/45.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/45.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/45.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/45.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/45.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/45.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/45.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/45.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/45.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/45.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
%     tx1 = ['train/aug_data/67.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/67.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data/67.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/67.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/67.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/67.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/67.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/67.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/67.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/67.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/67.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/67.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
    tx1 = ['train/aug_data/90.0_1_0/' listing(imgNum).name];
    tx2 = ['train/aug_gt/90.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
    fprintf(fid,'%s %s\n',tx1,tx2);
    tx1 = ['train/aug_data/90.0_1_1/' listing(imgNum).name];
    tx2 = ['train/aug_gt/90.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
    fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/90.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/90.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%      tx1 = ['train/aug_data_scale_0.5/90.0_1_1/' listing(imgNum).name];
%      tx2 = ['train/aug_gt_scale_0.5/90.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%      fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/90.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/90.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/90.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/90.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
%     tx1 = ['train/aug_data/112.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/112.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data/112.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/112.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/112.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/112.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/112.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/112.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/112.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/112.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/112.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/112.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
%     tx1 = ['train/aug_data/135.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/135.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data/135.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/135.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/135.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/135.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/135.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/135.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/135.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/135.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/135.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/135.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
%     tx1 = ['train/aug_data/157.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/157.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data/157.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/157.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/157.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/157.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/157.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/157.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/157.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/157.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/157.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/157.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
    tx1 = ['train/aug_data/180.0_1_0/' listing(imgNum).name];
    tx2 = ['train/aug_gt/180.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
    fprintf(fid,'%s %s\n',tx1,tx2);
    tx1 = ['train/aug_data/180.0_1_1/' listing(imgNum).name];
    tx2 = ['train/aug_gt/180.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
    fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/180.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/180.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/180.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/180.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/180.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/180.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/180.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/180.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
%     tx1 = ['train/aug_data/202.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/202.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data/202.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/202.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/202.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/202.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/202.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/202.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/202.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/202.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/202.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/202.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
%     tx1 = ['train/aug_data/225.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/225.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data/225.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/225.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/225.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/225.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/225.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/225.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/225.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/225.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/225.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/225.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
%     tx1 = ['train/aug_data/247.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/247.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data/247.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/247.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/247.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/247.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/247.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/247.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/247.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/247.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/247.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/247.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
    
    tx1 = ['train/aug_data/270.0_1_0/' listing(imgNum).name];
    tx2 = ['train/aug_gt/270.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
    fprintf(fid,'%s %s\n',tx1,tx2);
    tx1 = ['train/aug_data/270.0_1_1/' listing(imgNum).name];
    tx2 = ['train/aug_gt/270.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
    fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/270.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/270.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/270.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/270.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/270.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/270.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/270.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/270.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
%     tx1 = ['train/aug_data/292.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/292.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data/292.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/292.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/292.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/292.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/292.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/292.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/292.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/292.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/292.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/292.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
    
%     tx1 = ['train/aug_data/315.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/315.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data/315.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/315.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/315.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/315.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/315.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/315.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/315.0_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/315.0_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/315.0_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/315.0_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     
%     tx1 = ['train/aug_data/337.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/337.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data/337.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt/337.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/337.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/337.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_0.5/337.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_0.5/337.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/337.5_1_0/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/337.5_1_0/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
%     tx1 = ['train/aug_data_scale_1.5/337.5_1_1/' listing(imgNum).name];
%     tx2 = ['train/aug_gt_scale_1.5/337.5_1_1/' strrep(listing(imgNum).name,'.jpg','') '.png'];
%     fprintf(fid,'%s %s\n',tx1,tx2);
      
end